### ISSUE TITLE
Keepass 2.30 throws "not compatible error" - Manjaro Linux Rolling Release Mono v. 4.0.4.1-1

### ISSUE THREAD

**Issue by ConorIA** [mitchcapper/KPEntryTemplates#1]
As described in the issue title, the latest release results in an incompatibility warning in Manjaro Linux using Mono v. 4.0.4.1-1 and Keepass 2.30-1.

**Comment by mitchcapper** [comment]
I apologize I do not have a mono linux setup to test this on and am a bit short on time.  If you can put together a Dockerfile to simulate the environment that produces the error I may be able to look further.  Otherwise you can also submit a debug log:
MONO_LOG_LEVEL=debug keepass2 &> logfile

and then attach that to the ticket and it may help.

**Comment by conorkickass** [comment]
Unfortunately Dockerfiles are way over my head. Here is the logfile output though. I should mention that this logfile is after a complete removal (pacman -Rnsc mono keepass) and re-install of mono and keepass.

[logfile.txt](https://github.com/mitchcapper/KPEntryTemplates/files/32165/logfile.txt)

**Comment by mitchcapper** [comment]
Unfortunately I don't see any errors in the logfile related to the plugin and do not currently have time to setup an environment to test it in manjaro.  Sorry!   You may be able to use an old version I am not sure what would have changed to cause the issue.

You can try a few other options to get better logs:
--debug
and also:
--debug --saveplgxcr
just run keepass with those and send those logs I can see if that helps at all.

**Comment by conorkickass** [comment]
That, unfortunately, gave me the output as an image. But it looks like it might have something useful.

![screenshot from 2015-11-11 15-00-26](https://cloud.githubusercontent.com/assets/870746/11101514/4ab0a7a4-8885-11e5-937a-56d7c17a700c.png)

**Comment by mitchcapper** [comment]
Thanks unfortunately I am not sure still.  If you are comfortable compiling you could try the DLL version and see if that results in different (looking at some other projects they mention that).  Unfortunately at this point I cannot look into it further.

**Comment by jdunn0** [comment]
I also have this issue on Gentoo Linux both with mono 2.10.9-r2 and mono 4.0.3.20 (upgraded after I found out mono 2.10.9-r2 is a somewhat old release of mono).
Running with --debug shows the same dialog as shown in the screen shot above.
Running with --debug --saveplgxcr resulted in the folder $HOME/.local/share/KeePass/D077DB19362733459FF5CC98683AC322/ being created.
The folder appears to have the KPEntryTemplates source code in it along with bin and obj directories with Debug and Release directories that appear to contain compiled DLLs.
I don't see any apparent log file though so I don't know if it would help to upload an archive of this folder.

**Comment by fnkr** [comment]
+1. I'm using Fedora 23.

**Comment by kabili207** [comment]
There are a LOT of errors in Mono's GDI+ code, and unfortunately it isn't very well maintained either. Although knowing it's a GDI+ issue means that Mono is having problems with one of the images used.

**Comment by x09** [comment]
![kpentry](https://cloud.githubusercontent.com/assets/1303927/18261814/dbf124f8-741d-11e6-8ce8-9693abb489e9.png)

I am using Fedora 24

p.s. how compile plugin from source code (under Linux)?

**Comment by x09** [comment]
i fix it.

1) download sources tar.gz
2) change all PNG files from Reosurces dir (convert color space to index color)
3) recreate plugin (keepass --plgx-create /path/to/unpacked/sources)
4) replace .plgx file (cp KPEntryTemplates-7.0.0.1.plgx /usr/lib/keepass/KPEntryTemplates.plgx)

**Comment by mitchcapper** [comment]
@x09 Thank you!   I will make this change to the source and get it updated. Sadly I did not have a linux UI box to test on.

**Comment by mitchcapper** [comment]
Can anyone on *nix try the attached plgx and confirm working now? thanks!
[KPEntryTemplates.zip](https://github.com/mitchcapper/KPEntryTemplates/files/458297/KPEntryTemplates.zip)

**Comment by x09** [comment]
![module](https://cloud.githubusercontent.com/assets/1303927/18301154/1d75527c-74f1-11e6-8d6e-11d35f806949.png)

working fine
