### ISSUE TITLE
Template Tab position issue - Linux

### ISSUE THREAD

**Issue by brackenhill-mob** [mitchcapper/KPEntryTemplates#10]
Please can the Template Tab be moved from the first position?

On Linux systems running Mono, focus is always given to the template tab but it displays the Entry tab data. You cannot view the data in any other tab (not just Template) until you click on the Entry tab.

Thanks

**Comment by brackenhill-mob** [comment]
Re-reading my opening remarks, I might not have been as clear as I might have been in my description!

I'm talking about what happens when you first open an entry. The Template tab has focus but the data displayed is that of the Entry tab. You cannot view any other tab until you've clicked on the Entry one.

**Comment by mitchcapper** [comment]
Does this still happen? Part of my problem is I have no way of testing on mono.  If you can confirm this is still a valid bug.

**Comment by brackenhill-mob** [comment]
I no longer use Keepass having switched to KeepassXC which is a Linux specific variant. Sadly it doesn't support plugins so I cannot test this.

**Comment by mrijke** [comment]
This still happens to me, Ubuntu 16.04 with mono 4.2.1.102+dfsg2-7ubuntu4.
(Also #11 still is an issue)

**Comment by Sanaki** [comment]
Issue still present on mono 5.10.1.47.

**Comment by mitchcapper** [comment]
So I have no idea on what this mono  bug is.   My best idea to work around this is to detect that it is linux and then NOT auto-focus on the template tab (as the plugin currently does). That may resolve it.  Happy compromise?

**Comment by Sanaki** [comment]
I'd be okay with that myself. I use far fewer templated entries than non-templated entries though, someone else may feel differently.

**Comment by arkhipenko** [comment]
Confirm this is still happening. Happy with the compromise solution.
