### ISSUE TITLE
Template tab "grows" window - Linux

### ISSUE THREAD

**Issue by brackenhill-mob** [mitchcapper/KPEntryTemplates#11]
Each time you click on the Template tab, the data entry window "grows" vertically so that eventually you cannot view data or the Cancel and OK buttons which has been pushed down and off the screen as there is no scroll bar.

Linux uses Mono to run KeePass2. This is the only template I've used which displays this issue.

**Comment by mitchcapper** [comment]
Are you saying you have other templates in KPEntryTemplates it doesn't happen on only one? Can you export just that one to a keepass file that I can test with?

**Comment by brackenhill-mob** [comment]
Attached as a zipped
[badtemplate.zip](https://github.com/mitchcapper/KPEntryTemplates/files/498733/badtemplate.zip)
 KeePass2 XML file

**Comment by Sanaki** [comment]
Issue still persists in 5.10.1.47. I see this issue on every template, not just one.

**Comment by mitchcapper** [comment]
I am not sure how to fix as I do not have a linux machine with a display server on it.  Using the template in windows does not cause the same issue to happen.

**Comment by Sanaki** [comment]
@mitchcapper While I currently lack the resources to set up a remote system for you to work with securely, I may have the opportunity soon enough. I'll let you know if so. This is a bug I have a vested interest in seeing fixed, but unfortunately I lack the time and experience to help fix it directly.

**Comment by brackenhill-mob** [comment]
@mitchcapper This is easy to do if you install Oracle's VM Virtualbox and install a Linux distro in the VM. I used Linux Mint when I found the box - I now run a Linux specific version (Keepassxc) so I can't use your template anymore.

HTH

**Comment by mitchcapper** [comment]
With keepass resize a similar issue happened.   I have redone all of the scaling issues and am going to close this (hoping they are both fixed).  If not please re-open.
