### ISSUE TITLE
Copy a Template to another KeePass

### ISSUE THREAD

**Issue by Stonebiter** [mitchcapper/KPEntryTemplates#15]
Hello together,
I created a bigger Template in KeePass2 with KPEntryTemplates-Plugin and it works fine in my KeePass2.
Now I want to bring that Template to another KeePass from a friend.
I am sure, I did it in the past, but I can´t remember...
Can anybody help me?

**Comment by mitchcapper** [comment]
You can copy the template entry itself from your template folder to the template folder on your friends.  Please note this issue tracker is for bugs, and this question is about keepass not this plugin (this is just a UI on top of KeePass's native template system).
