### ISSUE TITLE
plugin incompatible

### ISSUE THREAD

**Issue by WorldSeso7** [mitchcapper/KPEntryTemplates#2]
sorry for my English
I installed the plugin but I get this error
![error](https://cloud.githubusercontent.com/assets/4233569/11613147/a6f89428-9c16-11e5-9feb-b640adf7711a.JPG)

Keep Pass version is the latest available (2.30)
S.o. Win 10 
moreover also deleting the plugin from folder of the program can not remove the error

**Comment by jdunn0** [comment]
It appears, you may be on the wrong project page.
This project is for the KPEntryTemplates plugin.
The error message is talking about the KPFloatingPanel plugin.
That project is at https://github.com/mitchcapper/KPFloatingPanel.

**Comment by mitchcapper** [comment]
This is definitely for the other program, please file the bug on that project.  It is however odd that after deleting the PLGX the error still occurs (as it should not load plugins not there).  You may want to try a clean folder with it and see if it still happens.
