### ISSUE TITLE
Listbox's width [wish]

### ISSUE THREAD

**Issue by Rodny0** [mitchcapper/KPEntryTemplates#22]
Hello.
Is it possible to expand listbox's width?
![2017-06-15_132008](https://user-images.githubusercontent.com/13980328/27176955-680f9eb4-51cd-11e7-98bd-27bf0f43fe49.png)

**Comment by mitchcapper** [comment]
When you open the dropdown I assume it shows at the widest option?  Changing this however is not a problem. It is a minor tweak I can make in the next release.

**Comment by Rodny0** [comment]
No, it has the same fixed width, long options are truncated.
![2017-06-15_212959](https://user-images.githubusercontent.com/13980328/27196208-38532c6e-5212-11e7-8ca9-eb5ced138e27.png)

**Comment by Rodny0** [comment]
Thank you, it works perfectly.
