### ISSUE TITLE
Incompatible with latest release of KeePass (2.36) 

### ISSUE THREAD

**Issue by gonzalu** [mitchcapper/KPEntryTemplates#28]
Latest release of KeePass refuses to load the KPEntry plugin as incompatible.

**Comment by mitchcapper** [comment]
Closed dupe of #17 not a bug you are using an old version.

**Comment by mitchcapper** [comment]
Note if you follow the directions on that bug and still have an issue do please re-open it.

**Comment by gonzalu** [comment]
Thank you... my bad. I downloaded 7.6 and I guess Windows did not replace the file in the directory :( I forced the delete of the old file and re-copied it and now works great. Sorry for the dupe also :) 

Thanks for your efforts.. .your plugin is invaluable for me :) 7.6 working fine!
