### ISSUE TITLE
Query: Can I specify patterns for legal field value entries?

### ISSUE THREAD

**Issue by jamesdavidhoward** [mitchcapper/KPEntryTemplates#29]
When defining a Templated field (like the Phone Number in your credit card example), I currently have to select the 'generic' Field Type "Inline".  Is there any facility you know of in your plugin (or KeePass or its other plugins) allowing specification of a valid 'template' or format for a field?  Ideally, something like a regular expression that has to match the user's type-in...
> "(([1-9][0-9]{2})-){2}-[0-9]{4}"

(This example RE is for a US/Canada/... phone number, of course.)

**Comment by mitchcapper** [comment]
It would likely be possible to add code to do some sort of validation, but does not currently exist in my plugin. As this is the first request for regex value validation I am not sure the demand is high enough (and I am fairly low on time).  I will leave the ticket open however to see about in the future.

**Comment by jamesdavidhoward** [comment]
I am willing / interested in prototyping an implementation as I learn more about KeePass and how KPEntryTemplates employs the existing capabilities of KeePass and piggybacks on the existing storage methods and schema.  (I've got lots to learn.)

For example, storing named regular expressions in an additional entry within the [Templates] group, entry name "RegularExpressions", with one [Advanced]->"String Field" per RE, each a "Name" and "Value" pair.  Think:
`RE_Phone_NorthAm` `(([1-9][0-9]{2})[- .]?){2}[0-9]{4}`
`RE_CreditCard` `([0-9]{4} ?){3}[0-9]{4}`
Then, a template definition could give the validation RE by name - or just use the existing field data types "Inline", "Protected Inline", "Date", etc.  to use when filling in data of a normal entry in a normal group employing a pre-defined tamplate.

One can also imagine `/`_`match`_`/`_`replace`_`/ `pattern expressions, which would describe input format in the _`match`_ part, and output/export format (the _`replace`_ part) whenever a field is used or specified for value substitution like Auto-Type `{VariableName}`

I obviously have lots to learn about storage as currently implemented, interception points that a plugin can use and implement.  I may be completely off-base, here...

**Comment by mitchcapper** [comment]
So given that (I would imagine) people do not have a lot of template parents I think it may not be worthwhile to do a regex templating system (allowing named regexs for easier re-use).  I would implement it as follows:
Add a Regex Inline and Regex Protected Inline types.
These would then get an options button like the combo type does right now.
The options field you could enter the regex you want into.
You can store the regex just like combo stores options.
 On focus lost from that textbox regex validation would be done, if an error the field could be highlighted in red.  A message box could be shown but might be somewhat annoying and the red box may get the same message across.

match/replace is tricky as the user edits it and then it replaces again, It could auto-format text but I am not sure that is worth the additional complications.

Just some thoughts.

**Comment by Sanaki** [comment]
Realistically, I would think anyone using regex fields in a template should be able to handle adding the patterns as advanced string fields. Still, it's hard to know how people use it in general. Most users aren't on github.

**Comment by mitchcapper** [comment]
I would probably turn down a PR that required editing the advanced string fields directly as the interface would be not intuitive.  There is already the input box pattern for listbox/combo box that would work here to get the regex.

**Comment by Sanaki** [comment]
Fair enough. Can't say that I know too much about the finer details of keepass addons.

**Comment by mitchcapper** [comment]
KPEntryTemplates code is broken out between the editor and the child viewer.  My recommendation would be to largely follow the listbox implementation for the editor and then the standard inline box for the viewer just attaching on onfocuslost (or whatever the term the form uses) handler that checks against the regex and turns the field red or green based on matches (or maybe red and no color if you want something more subtle).

**Comment by mitchcapper** [comment]
I am going to close this for now but PR welcome!

**Comment by Suncatcher** [comment]
It would be nice feature
