### ISSUE TITLE
Update Check says update is available but there is no update

### ISSUE THREAD

**Issue by jdunn0** [mitchcapper/KPEntryTemplates#3]
For the past week or so when I run KeePass, this update dialog appears:
![keepass update check - entry templates plugin](https://cloud.githubusercontent.com/assets/9695075/11969535/7e773ee4-a8cf-11e5-8f28-40eb3454d519.png)
It shows an update available for the Entry Templates plugins but there doesn't appear to be an update available.

**Comment by MasterMik** [comment]
Here the same.

**Comment by nmusatov** [comment]
It is just because in http://mitchcapper.com/keepass_versions.txt  (url plugin uses to check updates)
noted that last version for KPEntityTemplates is 7.0.0.1, but there is only 7.0 in releases here.
Mitch, could you please fix this versions inconsistency ?
Thanks.

**Comment by mitchcapper** [comment]
Very sorry for the delay, there was a minor bug fix and it seems the version file got updated before GitHub.  New release is up.
