### ISSUE TITLE
KPEntryTemplate not pulling same info as reg. KP Entry for Notes

### ISSUE THREAD

**Issue by Wild13c** [mitchcapper/KPEntryTemplates#30]
Mitch, I just noticed that when I have a clickable URL in the Notes section of Keepass, the URL only comes over as plain text in my KPEntryTemplate Notes Field which is linked to the KP Notes Field,  instead of the clickable URL that is in the Std. Keepass Entry Notes section.   I am not sure if this is by design but it would be nice if it could inherit the clickable URL.   Easy way to verify is to put a URL link in the Std. Keepass Notes section and it turns into a clickable link.  Then check KPEntryTemplates Notes Field and it will be plain text.

**Comment by Wild13c** [comment]
Mitch, I am including the following for clarification of the issue where the clickable links in the std. keepass entry window turns into non-clickable links in the KPET window.

 
[Non clickable links.docx](https://github.com/mitchcapper/KPEntryTemplates/files/1992910/Non.clickable.links.docx)

**Comment by mitchcapper** [comment]
@Wild13c thanks.  We are using a standard textbox for the notes field,  KeePass must be using a slightly rich textbox I haven't had a chance  yet to see if there is an issue swapping the KP Notes one for the standard textbox.

**Comment by mitchcapper** [comment]
@Wild13c  please test #39 I have added this

**Comment by Wild13c** [comment]
Mitch, I tried 2.39 and it still does not allow for clickable links.  I checked existing links and created a new entry, all of which still have no clickable link.  I checked the template and the field type is inline and is not changeable for the notes field.

**Comment by mitchcapper** [comment]
@Wild13c please see #39, you must create a rich textbox item in your template for it to work

**Comment by Wild13c** [comment]
As soon as I try to edit the notes field it pulls a field type of inline which cannot be changed to richtext box.
If I create a new notes field and assign the type as richtext box it no longer pulls the original entries from the keepass notes field.  Also, when I tested the link that was created in the richtext box if I clicked anywhere in the box the link was selected instead of just being able to click on the single link.

**Comment by Wild13c** [comment]
Mitch, just making sure I understand.   KPET cannot pull the contents of the notes field from the Keepass entry window and cannot have clickable links come over from the Keepass entry window?  The reason is because I have to assign the rich textbox as the type and not the inline that the notes field normally uses.  I saw what you were talking about the "Click Anywhere" but have never experienced it since I generally have multiple links and content in my notes.

**Comment by mitchcapper** [comment]
KPET can easily pull the contents of the notes field, just select "Notes" from the "Field" column.
Due to the bug mentioned in #39 I did not want to default the Notes field to be of rich type rather than inline as it would degrade the existing experience.  I think with the next release of KP the return bug will be fixed and then I can make it the default.

**Comment by Wild13c** [comment]
Gotcha, thanks for the clarification.  Also, wanted to say thanks for your support and KPET.
