### ISSUE TITLE
Incompatibility with Keepass 2.38

### ISSUE THREAD

**Issue by svenssonaxel** [mitchcapper/KPEntryTemplates#32]
Keepass 2.38 is now in debian sid.
When Keepass 2.38 starts with KPEntryTemplates, it says that the plugin is incompatible with this version of Keepass.

**Comment by IncPlusPlus** [comment]
I'm using this plugin on Windows 10 (64-bit) with Keepass 2.38. I'm not having this issue so it would seem it is unique to your OS.

**Comment by svenssonaxel** [comment]
The issue was in debian packaging of keepass, not in KPEntryTemplates: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890843

**Comment by mitchcapper** [comment]
Thanks for figuring this out!
