### ISSUE TITLE
Drag and drop entires into formulars

### ISSUE THREAD

**Issue by SanchoandPancho** [mitchcapper/KPEntryTemplates#36]
Hello, 

If it it possible, I wish an option to drag and drop the entries into formulars, because the order of formular fields in for e.g. registration formulars differs - and auto-fill doesn't fills correctly.

Thanks

**Comment by mitchcapper** [comment]
I think you are saying you want to drag entities from keepass into other applications correct?

**Comment by SanchoandPancho** [comment]
Yes. For e.g. Chrome, Firefox or Edge, to fill out formulars (Name, Country, Phone email, ...)

**Comment by Sanaki** [comment]
This is more in the scope of the Kee plugin, which already covers this functionality.
