### ISSUE TITLE
Add/Edit Template tab's Option column width unable to expand due to scroll bar

### ISSUE THREAD

**Issue by iamhammer** [mitchcapper/KPEntryTemplates#40]
When creating or editing a Template, on the Template tab there is a table with 5 columns. The table appears to have a fixed width. Expanding the `Field` or `Type` columns appear to subtract from the width of the `Title` column. No complaints there. The `Field Name` column appears to be get it's width from the column's contents, also cool.

**The problem is that the user is unable to expand the Option column**, because attempting to do so mouses over the vertical scroll bar, losing focus of the resize and setting the width back to where it was.

I'd like to see if the all of the columns subsequent to Title get their width from their contents, just as `Field Name` does.
Thank you.

![image](https://user-images.githubusercontent.com/1703116/39936921-174e2c36-551c-11e8-9256-cf62f04a6bae.png)

**Comment by mitchcapper** [comment]
Why do you want to expand the option column? The only item in the option column is a button that says "Opt".

**Comment by iamhammer** [comment]
If we could hide the column, rather than have a truncated width, wouldn't that also solve issue #41 ?
A horizontal scrollbar wouldn't be created, which in turn creates the vertical scrollbar.

**Comment by mitchcapper** [comment]
Do you have the text size or scaling turned up? As by default it doesn't do that.
Per #41: What platform are you on? What resolution, what DPI/scaling, what keepass version?

**Comment by iamhammer** [comment]
I'm using keepass 2.39 for the purposes of testing the KPEntryTemplates preview. I have not changed the default or recommended display settings of either machine as I happen like them that way.

On Windows 10:
Monitor 1: 3840 x 2160 with 250% scaling
Monitor 2: 1920 x 1080 with 100% scaling

On Windows 8.1: 1920 x 1080
Defaults (125% scaling)

This specific issue looks to be mitigated on Windows 8.1,
![image](https://user-images.githubusercontent.com/1703116/39947308-6b431ac2-553f-11e8-882c-f32e3d190030.png)

**Comment by rangerxusa** [comment]
Just adding that I am having the same issues. Windows 10 (will try Windows 8.1 but in the past have had the same problem. The Edit Entry window of template child is distorted until I resize the windows (and then the buttons are wrongly aligned to the right) and also the edit entry template parent windows has unnecessary vertical and horizontal scroll bars.
- Using KeePass 2.39.1 with Windows 10 display scaling at 100% or 125% and KPEntryTemplate.plgx 7.8 beta and no KeeResize.pglx - template child is fine and template parent has unnecessary scroll bars.
- Using KeePass 2.39.1 with Windows 10 display scaling at 100%  or 125% and KPEntryTemplate.plgx 7.8 beta AND KeeResize.pglx - template child is distorted and resize of window makes it somewhat better but the remove as template child button is right justified and the OK button is not visible. Template parent has unnecessary scroll bars.

So the display scaling seems to have no impact on the problem.
Without KeeResize.pglx the only issue is the unnecessary scroll bars in the template parent.
With KeeResize.pglx the template child (and other edit entry windows are distorted. Resizing windows helps somewhat but still not very usable.

**Comment by mitchcapper** [comment]
I am closing this in favor of #41 so we can avoid double conversations.
