### ISSUE TITLE
Questions on Field Names

### ISSUE THREAD

**Issue by TonyGravagno** [mitchcapper/KPEntryTemplates#42]
I'm curious about the choice of custom field names that come with the software. Most are \_etm_options_**foo**, but a couple are \_etm_options_**@foo**. Is there some implied or functional significance to the @ sign?

When an entry is posted for custom field \_etm_options_**Suffix**, the data is stored in custom field **Suffix**. Is that 100% consistent?

Related, (probably more of a KP question) field names can include spaces. In databases we're used to field names being more terse and with specific rules. For example "app_id" versus "Application ID". Are there any caveats for creating a field name like "_etm_zzz_Application ID", which results in data stored in field "Application ID"?

And ... is there a preferred forum/channel for asking questions about this plugin? @mitchcapper where do you hang out? :)

Thanks.

**Comment by mitchcapper** [comment]
- @ names are for special fields to separate out the logic for how they are handled from standard fields.    In quickly glancing at the code there are only:
```@exp_date @confirm @override```.  @confirm is ignored in terms of saving data out (It's just the password confirm field).  The entry expiry date and override URL just have custom logic in keepass backing.

- There are no downsides as far as I am aware to using spaces in field ID's (although likely improves readability slightly).  Coming from a computer background I too often find myself naming fields without spaces however.

I am @mitchcapper in gitter but without a community it is somewhat hard to DM.  I setup https://gitter.im/KeePassUnofficial/Plugins which should work.   Also on IRC but less frequently checked.
