### ISSUE TITLE
Rename _etm_template_uuid (problem with KPEnhancedEntryView)

### ISSUE THREAD

**Issue by malore** [mitchcapper/KPEntryTemplates#49]
"_etm_template_uuid" always appears as the first custom field in KPEnhancedEntryView. Is it somehow possible to move it out of sight?

**Comment by mitchcapper** [comment]
unfortunately no plans to do so it would require mass updating entries or a slow migration.  You could manually rename it and recompile yourself.  It might be better to see if KPEnhancedEntryView added a filter option.

**Comment by malore** [comment]
I reported it to the KPEnhancedEntryView developer and he replied:

> Using custom fields to hold hidden data like that is deprecated as of KeePass 2.35, released about a year ago. Plugins should now use [PwEntry.CustomData](https://keepass.info/help/kb/kdbx_4.html#extobj).
