### ISSUE TITLE
template list limited?

### ISSUE THREAD

**Issue by netdiver60** [mitchcapper/KPEntryTemplates#5]
Hi Mitch Capper

Can it be that the maximum number of templates in the selection list 30 is limited?
If so, can you change that?

![image](https://cloud.githubusercontent.com/assets/17419852/13240016/0d8c8ea0-d9df-11e5-83ea-dc5243b1943a.png)

Ideal would be an unlimited number of records which could be selected through a search box.

I would also be willing to pay something for this adaptation.

Netdiver 60

**Comment by mitchcapper** [comment]
This is actually a limitation of keepass and not the plugin (that's the native template support doing that).  I would assume it should be possible to.  I think the best option might be for the template folder to support sub folders so you could better organize your templates.

**Comment by mitchcapper** [comment]
Also I will note if you very much want this feature message me offline and we can talk further, otherwise suggesting it to keepass may get it eventually implemented.
