### ISSUE TITLE
Incompatible with KeePass 2.40

### ISSUE THREAD

**Issue by TheBudda** [mitchcapper/KPEntryTemplates#50]
This does not work with KeePass 2.40 I get a pop up telling it is not compatible

**Comment by Ornitho** [comment]
The same  as above : Does not work with KeePass 2.40 I get a pop up telling it is not compatible....

**Comment by EdgewalkerBlue** [comment]
https://github.com/mitchcapper/KPEntryTemplates/issues/35#issuecomment-426264096

Get it ,this version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.40

> This does not work with KeePass 2.40 I get a pop up telling it is not compatible

**Comment by TheBudda** [comment]
Thanks for the reply and info. It works now
