### ISSUE TITLE
Not Working with version 2.40

### ISSUE THREAD

**Issue by dev-pra** [mitchcapper/KPEntryTemplates#51]
I get an error when I start KeePass that the plugin is incompatible with the version.
Error Message: ![keepass issue](https://user-images.githubusercontent.com/7099459/46471657-38d84000-c7e3-11e8-8bbd-3995110e3073.png)

Keepass Version: 
![keepass version deatils](https://user-images.githubusercontent.com/7099459/46471726-8785da00-c7e3-11e8-9e6a-e6209d840ced.png)

**Comment by EdgewalkerBlue** [comment]
https://github.com/mitchcapper/KPEntryTemplates/issues/35#issuecomment-426264096
Get it ,this version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.40

**Comment by ZQRui** [comment]
> [#35 (comment)](https://github.com/mitchcapper/KPEntryTemplates/issues/35#issuecomment-426264096)
> Get it ,this version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.40

Where could find the version (7.8.0.0) of this Plugin? I can not find it in 
 https://github.com/mitchcapper/KPEntryTemplates

**Comment by Javaru** [comment]
> 
> 
> > [#35 (comment)](https://github.com/mitchcapper/KPEntryTemplates/issues/35#issuecomment-426264096)
> > Get it ,this version (7.8.0.0) of the Plugin also works on Win10 on KeePass 2.40
> 
> Where could find the version (7.8.0.0) of this Plugin? I can not find it in
> https://github.com/mitchcapper/KPEntryTemplates

@ZQRui - Issue #35 has the link to download it. In fact the "[#35 (comment)](https://github.com/mitchcapper/KPEntryTemplates/issues/35#issuecomment-426264096)" link at the top of the message you quoted will tkae you right to the comment with the link for v7.8.0.0, namely https://github.com/mitchcapper/KPEntryTemplates/files/1994132/KPEntryTemplates.zip

**Comment by CaptainPalapa** [comment]
I'm confused, kinda.  If we have a version of the plugin that works with
the latest version of KeePass...  why is it just ... not mainstream yet?

>

**Comment by mitchcapper** [comment]
@CaptainPalapa per my comment near the bottom of #35 there were other code changes merged in that I need to resolve or roll back.  Hopefully within the next week or two.

**Comment by mitchcapper** [comment]
Thanks @Javaru and @EdgewalkerBlue for assisting.

**Comment by Wild13c** [comment]
Mitch has a job and he is too busy right now to release the new version of which he is still trying to resolve some issues with.  He has been kind enough to fix the compatibility issue with Keepass 2.39.1 and above so that it works until he can do a proper release of the software.  #35 (comment)
Version (7.8.0.0)

**Comment by CaptainPalapa** [comment]
Ah, makes sense.  Yah, jobs.  Ugh!

>
