### ISSUE TITLE
Gallery of examples

### ISSUE THREAD

**Issue by bquistorff** [mitchcapper/KPEntryTemplates#55]
Is there a gallery of common examples anywhere (e.g. credit card)? This would both motivate more plugin adopters and make the plugin easier to use. Templates could provided as KeePass files with a single group with a single entry in them (easy to export/import from KeePass).

**Comment by Sanaki** [comment]
Far as I remember the plugin originally generated some example templates on first run, but it doesn't seem to do that anymore. As far as I'm personally aware, there is no "workshop" of templates anywhere. I definitely support this idea.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
how about a sampletemplate.kdbx in repo? Than you can copy paste what you need and add new thinkgs for usage for other people :) just my thought

**Comment by mitchcapper** [comment]
That sounds great:) Anyone want to create it? Happy to bundle it in.

**Comment by IncPlusPlus** [comment]
I've got a decent list of templates I could provide that I've been making and using for a while. I'll put them in a non-password protected kdbx file so that people can import them. I'll try to to this when I'm off from work but if I forget feel free to give me a ping.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Ok nice. What about the existing default templates? A community templates would lack multilingualism. May use defaults as linked reference fields. For customisations instead invented wheel from beginning?

**Comment by IncPlusPlus** [comment]
I'm sorry. I'm not sure what you mean. Which existing default templates did you have in mind? Also could you explain the last three sentences? I think some of your intent is getting lost in translation here.

**Comment by mitchcapper** [comment]
@IncPlusPlus thanks. I can add some screenshots and host the kdbx file with them.
@4-FLOSS-Free-Libre-Open-Source-Software  these are not "built-in" but rather a separate keepass file with them already defined as a sample.  You could copy them to your keepass file, and edit the titles if the language does not match your desire.

These are only samples @IncPlusPlus is doing.

**Comment by mitchcapper** [comment]
Thanks try this attachment.  It has the template folder set and some actual designs of the samples.   [StarterWithTemplates.zip](https://github.com/mitchcapper/KPEntryTemplates/files/3328035/StarterWithTemplates.zip)

**Comment by DoctorMG** [comment]
How can I open it? 
... it wants a password.

**Comment by mitchcapper** [comment]
finally closed:)
