### ISSUE TITLE
KPEntryTemplates 7.8 Pre-Release - Display Issues with KeeResize

### ISSUE THREAD

**Issue by sugodev** [mitchcapper/KPEntryTemplates#56]
Hello,

I really enjoy KPEntryTemplates (it is easily my favorite KeePass plugin), but I am experiencing some display issues. I am using KeePass 2.41.  I have upgraded KPEntryTemplates to the 7.8 pre-release. Also, I am using KP on Windows 7 64-bit.

Here are some screen captures of the display issues I am experiencing with KPEntryTemplates installed. 

Image 01.

Immediately after clicking 'Init as Template'.

KeeResize is installed.

Notice the wide 'Title' column, and the wide 'Remove as Template' button which is forcing right. This button is aligning to the far-right of the dialog window. (Perhaps it could be coded to align to the far-left side to minimize potential layout issues?)  Also, KPEntryTemplates is displaying this dialog window height at the maximum screen height. No user adjustments to this window's settings (window placement, window height, window width) are retained, even though KeeResize is installed, and seems to work fine everywhere else in the app (with RegInfo.ini and with the corresponding option to remember these window settings enabled).

![01  Immediately after clicking Init as Template (with KeeResize Installed)](https://user-images.githubusercontent.com/49222505/55454096-66842300-5593-11e9-98a3-954c6a14f460.jpg)

Image 02.

KeeResize is still installed.

The only resizing possible is dragging the edge of the window to the right.

![02  Only adjustment possible is dragging right (with KeeResize Installed)](https://user-images.githubusercontent.com/49222505/55454112-756ad580-5593-11e9-820e-0ca942e43646.jpg)

Image 03.

KeeResize has been uninstalled for this test. 

KPEntryTemplates remains installed, obviously.

Immediately after clicking 'Init as Template'. 

The window sizes are normal this way, but only after removing KeyResize. It seems like KPEntryTemplates is conflicting with KeyResize?

![03  Immediately after clicking Init as Template (with KeeResize Uninstalled)](https://user-images.githubusercontent.com/49222505/55454118-7ac82000-5593-11e9-94fc-0e861df97129.jpg)

Image 04.

Leaving the 'Templates' tab by clicking on the 'Entry' tab.

Notice the password icons on right.  

Also, notice the 'URL', 'Password', and 'Notes' fields are extending to the far right of the window, and aligning right, just as the 'Init As Template' (and 'Remove As Template') buttons do. 

There are actually several more fields for this template, but everything below the textbox has become jumbled together, and even scrolling to this portion is curiously unavailable. 

KeeResize is not installed for this test. 

![04  Leaving Templates tab (KeeResize Uninstalled)](https://user-images.githubusercontent.com/49222505/55454126-83b8f180-5593-11e9-8a12-63487c3afbac.jpg)

With KeyResize uninstalled, I get fairly normal component formatting initially, but the extended and right-aligning buttons and data fields problems still reoccur when switching back-and-forth between the 'Templates' and 'Entry' tabs.

Hopefully this information is helpful in improving the KPEntryTemplates plugin. Thank you for your kind help.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
KeyResize is a trial version or how i do check?
