### ISSUE TITLE
Placeholders templating for templates definition

### ISSUE THREAD

**Issue by Suncatcher** [mitchcapper/KPEntryTemplates#57]
I will explain what I mean. When one define the template we can specify correspondence between template field and the standard field alike 1-to-1 relation.

![Untitled](https://user-images.githubusercontent.com/6388034/58757728-04f01e80-851a-11e9-972d-74ae84a6fe37.png)

But what about not only 1:1 relation? What if to implement the possibility to make expressions with placeholders, substrings and other expressions? 
For example, I have a template for cellular carrier with fields Provider, WebUI user and country

![image](https://user-images.githubusercontent.com/6388034/58757751-526c8b80-851a-11e9-8b42-18f9ef91114d.png)

I wanna standard title entry field to be filled with **concatenation** of those three fields alike this:

    Verizon_JohnWoo_US

The templates can be set up like this

![image](https://user-images.githubusercontent.com/6388034/58757783-d4f54b00-851a-11e9-9277-b00cccffa482.png)

Is this hard to implement?

**Comment by mitchcapper** [comment]
I understand the request but yes it is would be complicated.  I think it would be hard to explain how to use, and I have no idea how to set the order.  I could concat each field with an _ that share the same name, but that in itself isn't straight forward.  How does one determine the order, and what character to join with.   I see it as limited use for others.  If it is extremely important for you ping me outside of here, but unless someone can provide a PR that isn't confusing to use I don't think it will be implemented.
