### ISSUE TITLE
"Two-Channel Auto-Type Obfuscation" won't be inherit from Template Parent

### ISSUE THREAD

**Issue by yaohunzhanyue** [mitchcapper/KPEntryTemplates#59]
If you follow this step : ctrl + i  -->  Template --> Set Template Parent
the "Two-Channel Auto-Type Obfuscation" won't inherit although it had been set.

**Comment by mitchcapper** [comment]
This would be due to the native code.  Templates have to apply at the creation of the entry for these things to apply.  While you can add a template parent for KPET afterwards keepass properties won't inherit after initial creation.
