### ISSUE TITLE
view of checkbox

### ISSUE THREAD

**Issue by scruel** [mitchcapper/KPEntryTemplates#62]
The view of checkbox are fine in edit window, and can change it's status easily:
![image](https://user-images.githubusercontent.com/16933298/60761572-00b9a280-a07e-11e9-8367-6c905e221713.png)

but not fin in the main window:
![image](https://user-images.githubusercontent.com/16933298/60761575-0f07be80-a07e-11e9-9242-0c8aa265f047.png)

Could you improve this?

**Comment by mitchcapper** [comment]
this is not clear, can you provide a bigger screenshot of the issue or be more detailed?

**Comment by scruel** [comment]
> this is not clear, can you provide a bigger screenshot of the issue or be more detailed?

Sorry, please check it again.

**Comment by mitchcapper** [comment]
I was not aware of that pane in the made window is that an addon or standard?  KPEntryTemplates certainly only works on the edit tab not that preview window.
