### ISSUE TITLE
[feature request] new field type: protected (multiline) textbox

### ISSUE THREAD

**Issue by Riajyuu** [mitchcapper/KPEntryTemplates#65]
Simply because I have several license keys like this:
![image](https://user-images.githubusercontent.com/16912240/64671576-6c423680-d458-11e9-9919-5855c38bf28e.png)
And I'm not gonna count as there are many lines below still.

**Comment by Sanaki** [comment]
If you need it protected, wouldn't it be better to just store it as an attachment? Keepass has a button to create a blank attachment, so it's rather easy to generate one quickly without having to rely on anything external.

**Comment by Riajyuu** [comment]
@Sanaki indeed. BUT it is given in email like that so multi-line textarea seems more natural

**Comment by Sanaki** [comment]
I'm not sure I understand where you have an issue, but if you've tried using attachments and they don't fill your need, I suppose that's all that matters.

**Comment by mitchcapper** [comment]
Closing this as current version does allow you to hit options on protected inline and specify # of lines to show.
