### ISSUE TITLE
Forum Security Questions and Answers

### ISSUE THREAD

**Issue by dai640** [mitchcapper/KPEntryTemplates#66]
![Snipaste_2019-12-03_23-24-25](https://user-images.githubusercontent.com/8486208/70064642-d7994000-1624-11ea-82c1-d6330afdcd6e.jpg)
In order to be safe, some forums must set security questions and answers. How to add these security questions and answers through templates? It can be populated automatically as well as username and password. Because his security issues are in order, 0-8. This type of field can be added to lastpass, and it can be automatically populated, which is quite convenient.

**Comment by dai640** [comment]
![Snipaste_2019-12-03_23-34-26](https://user-images.githubusercontent.com/8486208/70065275-c7ce2b80-1625-11ea-9623-705ce5d9e679.jpg)

Its security issues are in order, from the numbers 0-8, each number corresponds to a different qustions.

**Comment by mitchcapper** [comment]
KPEntryTemplates is only a UI assist tool for keepass.  As for how you could display them you could do one "security questions" box/field but that wouldn't support any 3rd party auto populating.  You could do Security Questions 1->8 in KPEntryTemplates which would create distinct fields.   To get it to fill in however would be beyond the scope of KPEntryTemplates and more on whatever filler you are using being able to pull those fields in.

**Comment by Sanaki** [comment]
Using [Kee](https://github.com/kee-org/browser-addon) to generate entries could probably auto-populate advanced fields to then use in a template, but that's the only way I can think of offhand, and it'd still require a little bit of tweaking and may not work reliably across sites.
