### ISSUE TITLE
How to hide "_etm_template_uuid"

### ISSUE THREAD

**Issue by liwenbus** [mitchcapper/KPEntryTemplates#67]
![001](https://user-images.githubusercontent.com/48404350/70231945-4ea21600-1796-11ea-96e0-b465b427f784.png)
![002](https://user-images.githubusercontent.com/48404350/70231951-53ff6080-1796-11ea-85f5-5a4248bd1756.png)
After I set the Templates, the _etm_template_uuid is allway showed on the KPEnhancedEntryView window. How can I hide the "_etm_template_uuid"?

**Comment by Sanaki** [comment]
That's outside the scope of this plugin. Ask the dev of KPEnhancedEntryView.

**Comment by liwenbus** [comment]
Hi, I ask the the dev of KPEnhancedEntryView, but he said it was caused by the KPEntryTemplates~
![0000](https://user-images.githubusercontent.com/48404350/70300174-c83b1200-1831-11ea-9e8e-6d981850dea5.png)

**Comment by Sanaki** [comment]
...weird. Well, perhaps I'm incorrect then. Also, I'm not a dev, just a misguided fool trying to help out where I can.

**Comment by mitchcapper** [comment]
@Sanaki  thank you for the assist.  @liwenbus it is correct that we create that field on an entry.  It is how the plugins knows what template to show for that entry.  This is what several plugins do to store data.  While KPEnhancedEntryView doesn't generate the fields it could give the users a global option to hide certain fields by default on entries as a work around. KeePass has a newer option for "CustomData" on entries that was introduced in the last file revision.  I have a prototype will likely push soon that allows storing data in this CustomData field instead but the conversion operation will also modify every keepass entry that has a template parent.

**Comment by liwenbus** [comment]
@mitchcapper Thank you so much.
