### ISSUE TITLE
Version 8.0 is not compatible with KeePass 2.43

### ISSUE THREAD

**Issue by rinaatt** [mitchcapper/KPEntryTemplates#68]
Hello not work your plugin, [proof screenshot](https://yadi.sk/i/6Nm0cma-ltc5zA).

**Comment by Sanaki** [comment]
Make sure you don't have a second copy somewhere in the program directory or subdirectories still. 8.0 is indeed compatible with 2.43.

**Comment by rinaatt** [comment]
I run KeePass2 on Linux Mint 19.2 under Mono (installed from https://download.mono-project.com/repo/ubuntu). I recheck installation and not find second copy of all.

P.S. Old version 7.8.0.0 is working.

**Comment by rinaatt** [comment]
I'm sorry, I need install mono-complete for compiling plugin.
