### ISSUE TITLE
No 'Init As Template' button on Template tab

### ISSUE THREAD

**Issue by Nick404800** [mitchcapper/KPEntryTemplates#73]
Hi, 
New to KeePass, Plugins and GitHub, so hope I'm not making a noobie mistake!  I added KPEntryTemplates.plgx to the KeePass Password Safe 2\Plugins directory, restarted KeePass and now see the Template tab in the Add Entry window.  However when I click on it the only button I have is 'Set Template Parent'.  There is no 'Init As Template' option.
![Add Entry](https://user-images.githubusercontent.com/70087446/90972854-d7005b00-e55f-11ea-9ea2-7b131f87f536.jpg)

Seeing and reading the 'Gallery of Examples' Issue, I thought it might help if I imported those templates, which I did.  However still no 'Init As Template' button on the Templates tab.  Also, when I open a record in the Items folder that was imported with and holds example records for the imported Templates, I get a dialog stating 'Unable to find parent template for this entry, removing as child'.  When I click on the Ok button for this dialog, I'm left looking at the Templates tab for the record with 'Set Template Parent' and nothing else.  If I click on 'Set Template Parent', I get the 'Select Parent Template Entry' window, but it is empty other than for the word 'Title'.
![Select Parent Template Entry](https://user-images.githubusercontent.com/70087446/90972747-23976680-e55f-11ea-967f-e7a534f8437b.jpg)

Have I missed a step with the plugin to get it working properly?

Cheers, Nick.

**Comment by majkaz** [comment]
Just for future reference:

Check, that the correct "Templates" group is initialized. 

I did the same, and there was a second group with the same name created on import. Either move the example templates, or point the settings to the imported group, not your empty one.

**Comment by GraphiteWingedBird** [comment]
Might have missed a step, check the [Installation section](https://github.com/mitchcapper/KPEntryTemplates#installation) of the ReadMe and make sure you defined which "Group" in KeePass is your "Template" group. All entries within that group should be bogus (I.e. no username or password that has relevance). The entries only exist as your template masters/parents.

1. Database Settings
![image](https://user-images.githubusercontent.com/81541678/113616155-c00c0600-9622-11eb-82b5-9ab90bd1d720.png)

2. Set the "Entry templates group" to the group in your database that exists for the purpose of holding templates.
![image](https://user-images.githubusercontent.com/81541678/113616768-88518e00-9623-11eb-924a-d9a9e6033c91.png)

**Comment by mitchcapper** [comment]
@GraphiteWingedBird thanks for putting such detailed instructions together.
