### ISSUE TITLE
How do I change from design view to entry view?

### ISSUE THREAD

**Issue by amccombsahce** [mitchcapper/KPEntryTemplates#77]
I am using KeePass v2.48.1 and KPEntryTemplates 8.0. When I click Add/Edit Entry > General tab, always shows Init As Template, then enter in the field names, however they do not appear when I click on the General tab, and I do not understand how, in the screenshots, that Add Entry and Edit Entry are both in the Template tab, how do I go from design view to entry view?
I created a new Group under the Database tree in the General entry; I would this that would be the proper place to set the templates, but it appears not to work that way, very confused.
The File > Database Settings > Advanced tab shows KPEntryTemplate, however I do not see how this would apply to a specific Group.

**Comment by mitchcapper** [comment]
Closing, sounds like they were not separated properly per the readme let me know if still an issue.
