### ISSUE TITLE
Udatecheck not working anymore

### ISSUE THREAD

**Issue by gusowski1** [mitchcapper/KPEntryTemplates#85]
https://mitchcapper.com/ doesn't respond anymore, therfore the updatecheck is not working anymore.

if you like i can provide a pull request with adding the version file directly to github code repo

**Comment by mitchcapper** [comment]
Sorry about that, I am planning a larger set of changes including changing the update system to be using a more modern keepass function setup.  In the mean time the server move finished states so should be working again.
