### ISSUE TITLE
Init As Template is not shown

### ISSUE THREAD

**Issue by averlon** [mitchcapper/KPEntryTemplates#87]
In my KeePass Entries I only get the Option on the Template Tab "Set Template Parent" but never the option to "Init As Template", although there is currently not Template setup.

How can I setup a Template?

**Comment by Wild13c** [comment]
https://github.com/mitchcapper/KPEntryTemplates

INSTALLATION

    Download from https://github.com/mitchcapper/KPEntryTemplates/releases

    Extract the plug-in (KPEntryTemplates.plgx) and place in the KeePass program directory

    Start KeePass and open a database

    In KeePass, click "Edit > Add Group" and name it something like "Templates", press Enter to finish adding the new group.

    Select "File > Database Settings..." and select the "Advanced" tab.

    In the "Templates" group set, set the "Entry templates group:" select the group you just created, and click "OK". This will close the database settings dialog and return you to the main application.

    **In the main application, select your "Templates" folder and click "Edit > Add Entry..."

    On the "Add Entry" dialog, select the "Template" tab and click "Init As Template"

    Build you new template by adding whatever fields you desire**

    Be sure to switch back to the "Entry" tab and enter the name of the template in the "Title" field.

    Once you are satisfied, click "OK" to save the template

    Your template is now ready to use when adding or editing entries
