### ISSUE TITLE
Unable to Install Properly

### ISSUE THREAD

**Issue by csgoss809** [mitchcapper/KPEntryTemplates#9]
I followed the instructions and placed the PLGX file in the proper directory, but when I open KeePass and go to Tools-->Plugins, it does not show up.

**Comment by mitchcapper** [comment]
What platform are you on? If you start with --debug is there any other output?  Do other PLGX plugins you put in the same folder work?

**Comment by csgoss809** [comment]
I'm on Windows 7 (64-bit). Using KeePass 1.31.  I've tried other PLGX plugins and they do not show up either. I'm not sure what you mean by --debug, sorry.

**Comment by KN4CK3R** [comment]
This is a 2.x plugin, it will not work with 1.31

**Comment by mitchcapper** [comment]
Thanks @KN4CK3R, he is correct closing.
